Update CODEOWNERS with integrations sections
opensearch-project/dashboards-observability pull request #1256
Opened 2023-11-16 19:00 UTC by Swiddis

### Description
Coming from #1252, this PR updates codeowners to:
- Use the Observability team within the org instead of listing every maintainer. This reduces maintenance overhead for the file.
- Adds myself and @YANG-DB as owners of the Integrations codebase.

### Issues Resolved
This makes some progress on #1252, but I think more owners should be identify before marking it as resolved. This is mostly meant to get the ball rolling.

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-16 19:00 UTC, YANG-DB approved these changes

2023-11-16 19:01 UTC, Swiddis commented on .github/CODEOWNERS
> +*   @opensearch-project/Observability
Looks like the team doesn't have write access, any workaround better than reverting?

2024-01-12 18:19 UTC, ps48 commented
I propose adding the code-owners as below:
Logs explorer: @mengweieric 
panels: @pjfitzgibbons 
app analytics: @paulstn 
notebooks: @ps48 
metrics: @kavithacm 
trace analytics: @RyanL1997 
Integrations: @Swiddis 
Datasources: @RyanL1997

2024-01-16 20:24 UTC, kavithacm approved these changes
Can you add Ryan as a maintainer before merging this PR?

2024-04-30 17:39 UTC, derek-ho requested changes
@Swiddis can we reach out to @pjfitzgibbons to see if he wants to be moved to emeritus prior to merging?

2024-06-19 22:16 UTC, closed without merging