Add Flint queries for Apache Access integration
opensearch-project/dashboards-observability pull request #1681
Opened 2024-04-09 23:48 UTC by Swiddis

### Description
Adds some queries with simple mappings. Future work needed for more complicated fields (like user agent parsing).

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-10 17:50 UTC, YANG-DB requested changes
Can you please update according with the next list guidelines
opensearch-project/opensearch-catalog#144

2024-04-10 18:27 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/apache/assets/create_table-1.0.0.sql
> +) USING csv
We can incrementally add formats, so it shouldn't be a blocker to add one now and add a parquet workflow in a second PR.

2024-04-10 18:29 UTC, Swiddis commented
> Can you please update according with the next list guidelines [opensearch-project/opensearch-catalog#144](https://github.com/opensearch-project/opensearch-catalog/issues/144)

Can you make this feedback more actionable? That's a large RFC and I'm not certain which parts I'm meant to apply right now.

2024-04-11 17:18 UTC, RyanL1997 approved these changes
LGTM. Just awaiting on addressing @YANG-DB's comments.

2024-04-11 18:09 UTC, YANG-DB commented
Hi
Table name 
MV query name 
Dashboard name 
Index pattern name 
Visualizations name

2024-04-11 19:32 UTC, Swiddis commented
Commented on the RFC, I don't think these changes are applicable to 2.13, and are at least out of scope for this PR.

2024-04-11 22:11 UTC, YANG-DB approved these changes

2024-04-15 21:48 UTC, YANG-DB approved these changes

2024-04-15 21:48 UTC, ps48 approved these changes

2024-04-15 21:49 UTC, paulstn approved these changes

2024-04-15 21:57 UTC, merged