Improve on ELB integration assets
opensearch-project/dashboards-observability pull request #1682
Opened 2024-04-10 17:46 UTC by seankao-az

### Description
Adjust queries for ELB integration.

- conform to OTEL schema for proprietary aws elb fields defined as such: https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/logs/aws/aws_elb-1.0.0.mapping
  - some table fields are mapped to multiple index fields
  - though some `aws.elb.*` fields defined today are not present in above definition, we still keep them
- adjust request parsing
- recursive lookup and compression for create table, for out of the box support for reading alb logs written to s3 by aws service

Some gaps about the mappings:
- missing OTEL fields
  - aws.elb.connection_time
  - communication.source.geo.country_name (required by visualization)
  - communication.source.geo.country_iso_code (required by visualization)
- unmapped ELB log fields
  - target:port_list
      - redundant because currently, this list can contain one item and it matches the target:port field.
  - target_status_code_list
      - redundant because currently, this list can contain one item and it matches the target_status_code field.
- mapped to some `aws.elb.*` field not present in https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/logs/aws/aws_elb-1.0.0.mapping
  - type
  - domain_name
  - chosen_cert_arn
  - actions_executed
  - redirect_url
  - lambda_error_reason
  - classification
  - classification_reason

#### Future Work
- workflow for each file format for creating table
- dashboard for Flint S3, collecting only the working visualizations (excluding the two that require country info)

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-10 17:48 UTC, YANG-DB requested changes
Can you please update according with the next list guidelines 
https://github.com/opensearch-project/opensearch-catalog/issues/144

2024-04-15 21:29 UTC, Swiddis approved these changes

2024-04-15 21:49 UTC, ps48 approved these changes

2024-04-15 21:49 UTC, YANG-DB approved these changes

2024-04-15 21:50 UTC, paulstn approved these changes

2024-04-15 22:30 UTC, RyanL1997 approved these changes

2024-04-15 23:06 UTC, merged