update vpc flow with flint-s3 based DDL assets and dashboard
opensearch-project/dashboards-observability pull request #1691
Opened 2024-04-15 04:31 UTC by YANG-DB

### Description
Add Flint S3 datasource support for VPC flow logs based integration
- include live query (week's worth data) MV
- include pre-aggregated MV queries
- include pre-aggregated MV window based queries
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-15 16:58 UTC, RyanL1997 reviewed
Hi @YANG-DB , thanks for putting these together. Just left some minor reviews.

2024-04-15 16:58 UTC, RyanL1997 commented on server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_agg_30min_connections_mv-1.0.0.sql
> +-- Enable for Auto refresh --
I think we still need to go with the auto refresh here. The empty index issue has been address by using different checkpoints when creating new MV.

2024-04-15 16:58 UTC, RyanL1997 commented on server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/create_table_parquet_vpc-1.0.0.sql
> + --- DDL VPC create table statement definition
should we include the integration name in the file name? I think for all of the pending PRs, we are just named it like `create_table-1.0.0`

2024-04-15 21:37 UTC, Swiddis commented
Also closes https://github.com/opensearch-project/opensearch-catalog/issues/143

2024-04-15 21:52 UTC, ps48 approved these changes

2024-04-15 23:19 UTC, RyanL1997 approved these changes

2024-04-15 23:56 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_agg_30min_connections_mv-1.0.0.sql
> +-- 30 Min Aggregation MV of VPC connections / bytes / packets
I think the file gets flattened at some point of install, so comments will cause issues

2024-04-15 23:58 UTC, Swiddis approved these changes

2024-04-15 23:58 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_agg_30min_connections_mv-1.0.0.sql
> +CREATE MATERIALIZED VIEW IF NOT EXISTS {table_name}_agg_30_min_connections_mview AS
```suggestion
CREATE MATERIALIZED VIEW IF NOT EXISTS {table_name}__agg_30_min_connections_mview AS
```

2024-04-15 23:58 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_agg_60min_connections_mv-1.0.0.sql
> +CREATE MATERIALIZED VIEW IF NOT EXISTS {table_name}_agg_60_min_connections_mview AS
```suggestion
CREATE MATERIALIZED VIEW IF NOT EXISTS {table_name}__agg_60_min_connections_mview AS
```

2024-04-15 23:58 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_live_week_mv-1.0.0.sql
> +CREATE MATERIALIZED VIEW {table_name}_week_live_mview AS
```suggestion
CREATE MATERIALIZED VIEW {table_name}__week_live_mview AS
```

2024-04-15 23:58 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_window-agg_60min_dest_ip_cardinality_mv-1.0.0.sql
> +CREATE MATERIALIZED VIEW IF NOT EXISTS {table_name}_window_agg_60_min_network_ip_bytes_mview AS
```suggestion
CREATE MATERIALIZED VIEW IF NOT EXISTS {table_name}__window_agg_60_min_network_ip_bytes_mview AS
```

2024-04-15 23:58 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_vpc_flow/assets/vpc_window-agg_60min_dest_ip_total-bytes_mv-1.0.0.sql
> +CREATE MATERIALIZED VIEW IF NOT EXISTS {table_name}_window_agg_60_min_network_ip_cardinality_mview AS
```suggestion
CREATE MATERIALIZED VIEW IF NOT EXISTS {table_name}__window_agg_60_min_network_ip_cardinality_mview AS
```

2024-04-16 00:06 UTC, Swiddis requested changes
^ Meant to request changes instead of approving

2024-04-16 21:47 UTC, Swiddis approved these changes
Tentatively approving assuming this runs, I haven't tested it locally but I don't see any obvious issues. Seems like active changes are still happening.

2024-04-18 03:44 UTC, merged