adding a link to the integrations catalog  release page
opensearch-project/dashboards-observability pull request #1863
Opened 2024-05-31 23:46 UTC by YANG-DB

### Description
adding a link to the integrations catalog  release page in the main integration page
![Uploading image (17).png…]()

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-03 16:38 UTC, rupal-bq approved these changes

2024-06-03 17:25 UTC, derek-ho commented on public/components/integrations/components/integration_header.tsx
> +          Catalog Page Link
```suggestion
          OpenSearch Catalog
```

I feel like page and link are redundant here, do we need UX review of these texts?

2024-06-03 17:51 UTC, Swiddis commented
My instinct is that this would be better placed as a button in the right, as a sort-of supplementary action, instead of in the description. Something like "View Catalog" with a hover-tooltip explaining something along the lines of "The Catalog is where new integration updates are released, which you can import to your cluster at any time"

<img width="1720" alt="Screenshot 2024-06-03 at 10 46 52 AM" src="https://github.com/opensearch-project/dashboards-observability/assets/31739405/34f65498-3292-40e8-bcaa-84f72ea1abb1">

2024-06-03 17:54 UTC, Swiddis requested changes
Failing unit tests (snapshots)

2024-06-07 21:21 UTC, Swiddis commented
Discussed with author and UX team: I'll be implementing the above button solution along with the upload button mentioned in #1867, closing this PR in favor of the new one.

2024-06-07 21:21 UTC, closed without merging