Add Apache Integration
opensearch-project/dashboards-observability pull request #754
Opened 2023-07-26 17:57 UTC by danieldong51

### Description
Created Apache schema, visual and query based assets including the dashboard, and sample data.

### Issues Resolved
#682 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-07-26 18:45 UTC, Swiddis requested changes

2023-07-26 18:45 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/apache/data/sample.json
> +            "device.name": "Mac"
`os.*` should be split into an object with sub-objects: `"os": {"name": "Mac OS X", ...}`. Same with `device.name`.

2023-07-26 18:45 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/apache/schemas/communication-1.0.0.mapping.json
> +                                "geo.country_iso_code": {
Opposite problem as with the user agent, `geo` should be an object instead of a segment of multiple fields.

2023-07-26 18:45 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/apache/info/README.md
> +Apache integration includes dashboards, visualisations, queries and an index mapping.
I gave this same comment to Lior earlier: in the READMEs we should have a description of how to set up an ingestion pipeline for this integration, if one is at all available. If one isn't available it's not a big deal.

2023-07-26 19:06 UTC, YANG-DB requested changes

2023-07-26 19:06 UTC, YANG-DB commented on server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
> +    "sourceUrl": "https://github.com/elastic/beats/tree/main/filebeat/module/apache/_meta/kibana/7/search",
source is our own repo for the integration:
`    "sourceUrl": "https://github.com/opensearch-project/dashboards-observability/tree/main/server/adaptors/integrations/__data__/repository/aws_s3/info",
`

2023-07-26 19:06 UTC, YANG-DB commented on server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json
> +            {
this is the correct structure :
````
  "statics": {
    "logo": {
      "annotation": "AWS VPC Logo",
      "path": "logo.svg"
    },
    "gallery": [
      {
        "annotation": "AWS VPC Flow Log Dashboard",
        "path": "dashboard1.png"
      }
    ]
  },
````

2023-07-26 19:06 UTC, YANG-DB commented on server/adaptors/integrations/__data__/repository/apache/schemas/user_agent-1.0.0.mapping.json
dont create a new component for user_agent - move this into existing http.mapping component

2023-07-26 19:06 UTC, YANG-DB commented on server/adaptors/integrations/__data__/repository/apache/schemas/logs-1.0.0.mapping.json
> +        "user_agent"
delete this - the `user_agent` should be inside http component

2023-07-26 19:06 UTC, YANG-DB commented on server/adaptors/integrations/__data__/repository/apache/schemas/http-1.0.0.mapping.json
add user_agent object mapping here

2023-07-27 22:51 UTC, YANG-DB approved these changes

2023-07-28 16:35 UTC, YANG-DB requested changes

2023-07-28 16:35 UTC, YANG-DB commented on server/adaptors/integrations/__data__/repository/apache/info/README.md
Please add an additional doc on setting up a docker compose that will showcase how to set an end-to-end flow with this integration using data-prepper : https://github.com/opensearch-project/data-prepper/tree/main/examples/log-ingestion

2023-07-28 16:40 UTC, Swiddis approved these changes

2023-08-02 00:58 UTC, YANG-DB approved these changes

2023-08-02 00:58 UTC, merged