Aws cloudfront integration
opensearch-project/dashboards-observability pull request #779
Opened 2023-07-31 18:48 UTC by YANG-DB

### Description
Create an aws cloud-front integration

### Issues Resolved
 - https://github.com/opensearch-project/dashboards-observability/issues/775

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-07-31 20:38 UTC, YANG-DB commented
https://github.com/opensearch-project/dashboards-observability/assets/48943349/1b94df4b-59fe-4604-ba7e-5ba799daf817

2023-08-01 16:52 UTC, derek-ho commented on server/adaptors/integrations/__data__/repository/aws_cloudfront/assets/aws_cloudfront-1.0.0.ndjson
> +{"attributes":{"fields":"[{\"count\":0,\"name\":\"@timestamp\",\"type\":\"date\",\"esTypes\":[\"date\"],\"scripted\":false,\"searchable\":true,\"aggregatable\":true,\"readFromDocValues\":true},{\"cou
What is up with the no data to display in the video? Is it keyword issue again, can we look into that @YANG-DB

2023-08-01 16:53 UTC, derek-ho requested changes
Requesting changes for no data panels in the dashboard

2023-08-03 21:33 UTC, derek-ho commented
Still seeing errors and no data panels

2023-08-03 22:37 UTC, Swiddis requested changes

2023-08-03 22:37 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_cloudfront/aws_cloudfront-1.0.0.json
> +  "type": "logs",
Errors on panels caused by type mismatch again

2023-08-04 15:51 UTC, anirudha approved these changes

2023-08-04 17:16 UTC, Swiddis approved these changes
Verified working in manual testing -- only complaints would be to find a better photo of the logo and remove redundant sample data files

2023-08-04 17:31 UTC, derek-ho approved these changes

2023-08-04 17:32 UTC, merged