aws WAF integration
opensearch-project/dashboards-observability pull request #788
Opened 2023-08-01 18:27 UTC by YANG-DB

### Description
AWS WAF is a web application firewall that lets you monitor HTTP(S) requests to your web application resource.

### Issues Resolved
- https://github.com/opensearch-project/dashboards-observability/issues/711

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [x] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-08-03 21:31 UTC, Swiddis requested changes
Fails during manual check: clicking `try it` on clean instance results in many erroring panels

2023-08-03 22:12 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_waf/aws_waf-1.0.0.json
> +  "type": "logs",
Type should be logs-waf, probably related to why it's failing

2023-08-04 15:52 UTC, anirudha approved these changes

2023-08-04 17:09 UTC, Swiddis approved these changes
Works in manual testing, some non-blocking issues

2023-08-04 17:09 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_waf/data/samples-raw.json
Not sure if we should ship with this since it takes up a lot of space and isn't used, but non-blocking

2023-08-04 17:09 UTC, Swiddis commented on server/adaptors/integrations/__data__/repository/aws_waf/static/logo.jpg
Possible to make this an SVG or PNG with a transparent background? This doesn't render well in dark mode

2023-08-04 17:49 UTC, merged